#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "$0" )" && pwd )"
ROOT_DIR="$SCRIPT_DIR"
LAUNCHER="$ROOT_DIR/out/cli/launcher/dest/launcher"
if ! test -e "$LAUNCHER"; then
(
   cd "$ROOT_DIR" || exit
   ./mill cli.launcher
)
fi
exec "$LAUNCHER" "$@"
