name: CI
on:
  push:
    branches:
    - debug
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  jvm-tests:
    timeout-minutes: 120
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.3
    - uses: coursier/setup-action@v1.2.0-M1
      with:
        jvm: "temurin:17"
    - name: JVM integration tests
      run: ./mill -i integration.jvm.test "scala.cli.integration.ExportMillTests212.JVM"
