name: CI
on:
  push:
    branches:
    - debug
    tags:
    - "v*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  jvm-tests:
    timeout-minutes: 120
    runs-on: ${{ matrix.OS }}
    strategy:
      fail-fast: false
      matrix:
        OS: ["ubuntu-latest"]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.3
    - uses: coursier/setup-action@v1.2.0-M1
      with:
        jvm: "temurin:17"
    - name: Copy launcher
      run: ./mill -i copyJvmLauncher artifacts/
      if: runner.os == 'Linux'
    - uses: actions/upload-artifact@v2.3.1
      if: runner.os == 'Linux'
      with:
        name: launchers
        path: artifacts/
        if-no-files-found: error
        retention-days: 2
    - name: Unit tests
      run: |
        ./mill -i unitTests
        ./mill -i bloop-rifle._.test
    - name: JVM integration tests
      run: ./mill -i integration.jvm.test "scala.cli.integration.ExportMillTests212.JVM"
